-- NariVibes — Product seed data (prices in paise)
INSERT OR REPLACE INTO products (id, name, material, price, category, collection, colors, sizes, description, details, images, stock, featured, badge, status) VALUES

('aurelia-linen-dress','Aurelia Linen Dress','Natural Linen',280000,'dresses','Summer 2024',
'[{"name":"Ivory","hex":"#F5F0E8"},{"name":"Sand","hex":"#C8B89A"},{"name":"Sage","hex":"#8A9B7C"}]',
'["XS","S","M","L","XL"]',
'Crafted from pure natural linen, the Aurelia Dress embodies effortless summer elegance. Its relaxed silhouette flows gracefully from a delicate smocked bodice to a sweeping midi length. Designed for the woman who moves through the world with quiet confidence.',
'["100% Natural Linen — pre-washed for softness","Hand-wash cold or gentle machine cycle","Lay flat to dry; do not tumble dry","Cool iron on reverse to preserve texture","Exclusive Summer 2024 Collection"]',
'["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80","https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80","https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"]',
18,0,NULL,'active'),

('riviera-sun-hat','Riviera Sun Hat','Woven Straw',120000,'accessories','Summer 2024',
'[{"name":"Natural","hex":"#D4B896"},{"name":"Honey","hex":"#C49A45"}]',
'["One Size"]',
'Hand-woven by artisans using traditional techniques, the Riviera Sun Hat is the ultimate companion for sun-drenched days. Its wide, structured brim offers generous shade while the grosgrain ribbon band adds a touch of refined detail.',
'["100% Natural Toquilla Straw — ethically sourced","Grosgrain ribbon interior band for comfort","Spot clean only with damp cloth","Store in the provided dust bag to retain shape","Handcrafted — minor natural variations are a mark of authenticity"]',
'["https://images.unsplash.com/photo-1517401836282-fa19f65a0ae8?w=800&q=80","https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80"]',
30,0,NULL,'active'),

('azure-silk-trousers','Azure Silk Trousers','Sandwashed Silk',250000,'trousers','Summer 2024',
'[{"name":"Azure","hex":"#6FA3C0"},{"name":"Ivory","hex":"#F5F0E8"},{"name":"Blush","hex":"#E8C4B8"}]',
'["XS","S","M","L","XL"]',
'The Azure Silk Trousers are a study in refined luxury — their sandwashed finish gives the silk a matte, lived-in softness that drapes impeccably with every step. A wide, elasticated waistband ensures comfort without sacrificing the clean, tailored line.',
'["100% Sandwashed Mulberry Silk","Dry clean recommended; hand-wash in cool water with silk detergent","Do not wring; roll in a towel to remove excess water","Steam to remove creases — do not iron directly","Fully lined with silk habotai"]',
'["https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=800&q=80","https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=800&q=80"]',
12,0,NULL,'active'),

('cami-silk-top','Cami Silk Top','Crepe de Chine',180000,'tops','Summer 2024',
'[{"name":"Champagne","hex":"#F0DEB4"},{"name":"Blush","hex":"#E8C4B8"},{"name":"Midnight","hex":"#2A2A3E"},{"name":"Ivory","hex":"#F5F0E8"}]',
'["XS","S","M","L","XL"]',
'The Cami Silk Top is sculpted from the finest Crepe de Chine — a fabric prized for its fluid drape and subtle matte sheen. Adjustable silk-covered straps and a gently curved neckline make it equally beautiful worn alone or layered beneath a linen blazer.',
'["100% Silk Crepe de Chine — 16 momme weight","Hand-wash cold or dry clean","Do not tumble dry; hang to air dry away from direct sunlight","Low iron on silk setting, reverse side only","Adjustable spaghetti straps with silk-covered hardware"]',
'["https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80","https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&q=80"]',
22,0,NULL,'active'),

('solano-leather-sandal','Solano Leather Sandal','Vachetta Leather',220000,'footwear','Summer 2024',
'[{"name":"Natural Tan","hex":"#C49A65"},{"name":"Cognac","hex":"#8B4513"}]',
'["35","36","37","38","39","40","41"]',
'The Solano Sandal is a love letter to the Italian Riviera — handcrafted from buttery Vachetta leather that develops a rich patina over time. A contoured footbed and hand-stitched straps mold naturally to the foot, making these sandals as comfortable as they are beautiful.',
'["100% Full-grain Vachetta Leather upper and footbed","Leather sole with natural rubber reinforcement","Handcrafted in limited quantities","Condition with leather cream periodically; avoid prolonged water exposure","Natural patina development is a hallmark of Vachetta leather"]',
'["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80","https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80"]',
14,0,NULL,'active'),

('classic-linen-shirt','Classic Linen Shirt','Pure White Linen',160000,'tops','Summer 2024',
'[{"name":"White","hex":"#FAFAF8"},{"name":"Ecru","hex":"#EDE0CB"},{"name":"Sky","hex":"#B8D4E3"}]',
'["XS","S","M","L","XL","XXL"]',
'The Classic Linen Shirt is an eternal wardrobe cornerstone, reimagined with precise tailoring and a slightly relaxed fit that flows beautifully in the summer breeze. Stone-washed European linen ensures a softness from the very first wear.',
'["100% European Stone-washed Linen — OEKO-TEX certified","Mother-of-pearl buttons","Machine wash cool, gentle cycle","Tumble dry low or line dry","Iron while slightly damp for a crisp finish; wrinkles are natural and part of its character"]',
'["https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&q=80","https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80"]',
35,0,NULL,'active'),

('silk-sun-dress','Silk Sun Dress','Sandwashed Silk',290000,'dresses','Summer 2024',
'[{"name":"Saffron","hex":"#F4A832"},{"name":"Ivory","hex":"#F5F0E8"},{"name":"Terracotta","hex":"#C0622D"}]',
'["XS","S","M","L","XL"]',
'The Silk Sun Dress is the centrepiece of the Summer 2024 Collection — a fluid maxi silhouette in the finest sandwashed silk that catches every shift of light. A tie-detail halter neck and open back create a sensuous yet graceful form.',
'["100% Sandwashed Mulberry Silk — 22 momme","Fully self-lined with silk charmeuse","Dry clean recommended; hand-wash cold as alternative","Steam to refresh; do not iron directly on silk","Adjustable halter tie neck for a custom fit"]',
'["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80","https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80","https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80"]',
8,1,'New Arrival','active'),

('riviera-sunglasses','Riviera Sunglasses','Acetate Frame',150000,'accessories','Summer 2024',
'[{"name":"Tortoiseshell","hex":"#8B5E2A"},{"name":"Ivory","hex":"#F5F0E8"},{"name":"Noir","hex":"#1A1A1A"}]',
'["One Size"]',
'Inspired by the golden era of French Riviera glamour, the Riviera Sunglasses marry oversized drama with everyday wearability. Crafted from Italian bio-acetate with polarised mineral glass lenses, they offer exceptional UV protection without compromising clarity.',
'["Italian bio-acetate frame — lightweight and hypoallergenic","Polarised mineral glass lenses with UV400 protection","Gold-plated stainless steel hinges","Includes hand-stitched suede case and microfibre cloth","Clean lenses with the provided cloth only"]',
'["https://images.unsplash.com/photo-1591561954555-607968c989ab?w=800&q=80","https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80"]',
20,0,NULL,'active'),

('woven-straw-tote','Woven Straw Tote','Natural Straw',180000,'accessories','Summer 2024',
'[{"name":"Natural","hex":"#D4B896"},{"name":"Natural/Black","hex":"#C4A882"}]',
'["One Size"]',
'The Woven Straw Tote is a summer essential that transitions from market mornings to seaside afternoons with ease. Hand-woven by skilled artisans using sustainably sourced straw, it features a supple leather interior, a zip-close inner pocket, and leather-wrapped handles.',
'["Sustainably sourced natural straw exterior","Full leather lining — Italian vegetable-tanned","Interior zip pocket and two open slip pockets","Leather-wrapped top handles; 30cm drop","Spot clean exterior; wipe leather interior with damp cloth"]',
'["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80","https://images.unsplash.com/photo-1591561954555-607968c989ab?w=800&q=80"]',
16,0,'Bestseller','active'),

('coastal-wrap-skirt','Coastal Wrap Skirt','Linen Blend',140000,'trousers','Summer 2024',
'[{"name":"Sand","hex":"#C8B89A"},{"name":"White","hex":"#FAFAF8"},{"name":"Stripe","hex":"#B8C9D4"}]',
'["XS","S","M","L","XL"]',
'The Coastal Wrap Skirt channels the effortless spirit of summer with its relaxed wrap silhouette and breathable linen blend fabric. A generous tie allows the fit to be adjusted to your preference, from a demure midi to a playful side split.',
'["55% Linen, 45% Cotton — pre-washed for softness","Self-tie wrap design with an adjustable fit","Machine wash cool, gentle cycle","Line dry recommended to preserve fabric integrity","Cool iron if required"]',
'["https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=800&q=80","https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=800&q=80"]',
25,0,NULL,'active'),

('tan-leather-sandal','Tan Leather Sandal','Full Grain Leather',180000,'footwear','Summer 2024',
'[{"name":"Tan","hex":"#B8864E"},{"name":"White","hex":"#F0EDE8"}]',
'["35","36","37","38","39","40","41"]',
'A pared-back summer staple, the Tan Leather Sandal is built on a single principle: that true quality requires no excess ornamentation. Full-grain leather upper straps and a padded leather footbed offer enduring comfort, while the slim profile and clean lines ensure it pairs with everything.',
'["100% Full-grain vegetable-tanned leather upper","Cushioned leather-wrapped footbed","Rubber-reinforced leather outsole for durability","Wipe clean with a slightly damp cloth; condition seasonally","Handcrafted — allow a short break-in period"]',
'["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80","https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80"]',
20,0,NULL,'active'),

('linen-wide-leg-pants','Linen Wide-Leg Pants','Premium Linen',220000,'trousers','Summer 2024',
'[{"name":"Ivory","hex":"#F5F0E8"},{"name":"Camel","hex":"#C9A96E"},{"name":"Black","hex":"#1A1A1A"}]',
'["XS","S","M","L","XL"]',
'The Linen Wide-Leg Pants redefine relaxed sophistication. Cut from premium Irish linen with a generous sweep through the leg, they move with the grace of a wider silhouette while remaining breathable in even the warmest climates.',
'["100% Premium Irish Linen — OEKO-TEX Standard 100 certified","Elasticated waistband with interior drawstring","Two side seam pockets","Machine wash cool; line dry for best results","Natural linen creasing is expected and part of the aesthetic"]',
'["https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=800&q=80","https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=800&q=80","https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"]',
19,1,NULL,'active');
